# Generated by Django 5.0.3 on 2024-03-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('OWNER', 'Owner'), ('EMPLOYEE', 'Employee'), ('CUSTOMER', 'Customer')], default='ADMIN', max_length=20),
        ),
    ]
