# Generated by Django 5.0.2 on 2024-04-04 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("street", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("daily", models.CharField(max_length=200)),
                ("sitename", models.CharField(blank=True, default="", max_length=200)),
                ("phone", models.CharField(max_length=20)),
                ("link1", models.CharField(max_length=20)),
                ("link2", models.CharField(max_length=20)),
                ("link3", models.CharField(max_length=20)),
                ("link4", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("resume", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("url", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Menu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("link", models.CharField(blank=True, default="", max_length=20)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("hasChild", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(blank=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("slug", models.SlugField(blank=True, max_length=200)),
                ("resume", models.TextField(blank=True, default="")),
                ("description", models.TextField(blank=True, default="")),
                ("url", models.CharField(blank=True, default="", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="MenuItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("link", models.CharField(blank=True, default="", max_length=20)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slug_name",
                        to="pages.menu",
                    ),
                ),
            ],
            options={
                "ordering": ["-title"],
                "indexes": [
                    models.Index(fields=["-title"], name="pages_menui_title_4f434a_idx")
                ],
            },
        ),
    ]
