# Generated by Django 5.0.2 on 2024-04-04 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="title",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
