# Generated by Django 5.0.2 on 2024-04-05 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0002_link_title"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="link1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="link2",
        ),
        migrations.RemoveField(
            model_name="address",
            name="link3",
        ),
        migrations.RemoveField(
            model_name="address",
            name="link4",
        ),
        migrations.AddField(
            model_name="address",
            name="facebook",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="address",
            name="instagram",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="address",
            name="linkedin",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="address",
            name="twitter",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AddField(
            model_name="address",
            name="youtube",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
