# Generated by Django 5.0.4 on 2024-04-05 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_menuitem_parent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menuitem',
            old_name='parent',
            new_name='menu',
        ),
    ]
