# Generated by Django 5.0.4 on 2024-04-06 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_rename_parent_menuitem_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('-title',)},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ('-title',)},
        ),
        migrations.AddField(
            model_name='address',
            name='github',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='facebook',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='instagram',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='twitter',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='youtube',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['-title'], name='pages_menu_title_f0fe2f_idx'),
        ),
    ]
