# Generated by Django 5.0.4 on 2024-04-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_menu_options_alter_menuitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='delay',
            field=models.CharField(blank=True, default='0.2s', max_length=4),
        ),
        migrations.AddField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='fa', max_length=20),
        ),
    ]
